# Matrix

In [74]:
import numpy as np

## Create Matrices

In [75]:
A= np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
B= np.random.random((3,3))
B

array([[0.20147439, 0.15105735, 0.08022594],
       [0.84696552, 0.47530222, 0.16676384],
       [0.87180369, 0.49248805, 0.99908437]])

In [77]:
# 3D matrix 
C = np.random.random((3,3,3))
C

array([[[0.23887191, 0.15462816, 0.5534093 ],
        [0.83750594, 0.66006365, 0.38456949],
        [0.48499366, 0.50117303, 0.27433906]],

       [[0.86466722, 0.20621068, 0.68426398],
        [0.18625618, 0.35363068, 0.14519649],
        [0.08085351, 0.30885535, 0.69268136]],

       [[0.57949838, 0.97970693, 0.81671027],
        [0.69541647, 0.11136814, 0.30457574],
        [0.41990102, 0.44052963, 0.77270872]]])

In [78]:
# identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## See Matrix details

In [79]:
print(A.ndim)

1


In [80]:
print(A.shape)

(10,)


## Index/ Slice

- [start: stop: steps, start: stop: steps]
- steps --> if 1 step
- note: slices are views (copy by reference)

In [81]:
# get x= 0, y = 2 for 3D array 

C[0, 2, :]

array([0.48499366, 0.50117303, 0.27433906])

### Practice

get colored subsets

<img src="https://github.com/cse6040/labs-fa17/raw/master/lab10-numpy/slicing-exercise.png" alt="Exercise: Extract these slices" width="240">

In [82]:
Z= np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
Z

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [83]:
# green
Z[2:: 2, 0::2]

array([[20, 22, 24],
       [40, 42, 44]])

### check whether share memory

In [84]:
np.may_share_memory(Z, Z.copy())

False

In [85]:
np.may_share_memory(Z, Z)

True

### Boolean mask

In [86]:
# boolean matrix if number is positive multiple of 3
mask = Z%3 == 0
mask

array([[ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False],
       [ True, False, False,  True, False, False],
       [False, False,  True, False, False,  True],
       [False,  True, False, False,  True, False]])

In [87]:
is_prime = np.empty(n+1, dtype = bool)
is_prime[:3]


array([[ True, False],
       [False, False],
       [False, False]])

## .norm

In [88]:
B

array([[0.20147439, 0.15105735, 0.08022594],
       [0.84696552, 0.47530222, 0.16676384],
       [0.87180369, 0.49248805, 0.99908437]])

In [89]:
B_norm = np.linalg.norm(B, ord=2, axis = 1)
B_norm

array([0.2642848 , 0.98543035, 1.41448072])

## .argmin
- axis default is flattened array

In [117]:
argmin1= np.argmin(B, axis = 1)
argmin1

array([2, 2, 1])

In [118]:
noob = np.unravel_index(argmin1, B.shape)
noob

(array([0, 0, 0]), array([2, 2, 1]))

In [119]:
B[noob]

array([0.08022594, 0.08022594, 0.15105735])

In [91]:
argmin= np.argmin(B, axis = 0)
argmin

array([0, 0, 0])

In [92]:
np.argmin(B)

2

## .unravel_index

In [120]:
arr = np.arange(40)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
np.unravel_idnex

# random.choice
- choice( 1D array/ int, size = int/ tuple, replace= True, p )
- if int used instead of array population, then sample generated as if it were np.arange(int)
- size by tuple i.e. (m, n, k ) = m* n * k
- replace -> sample replacement or not
- p -> probabilities associated with each data entry, else uniform

In [5]:
np.random.choice(5,2, replace = True)

array([0, 2])

## a) use len(arr) if array > 1D --> to randomize the row

In [32]:
# 2D array here
import seaborn as sns
iris = sns.load_dataset('iris')[:4]
iris_arr= iris.to_numpy()
iris_arr

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa'],
       [4.7, 3.2, 1.3, 0.2, 'setosa'],
       [4.6, 3.1, 1.5, 0.2, 'setosa']], dtype=object)

In [33]:
from numpy.random import choice
# get random rows
n = choice(len(iris), size= 2)
n

array([3, 1])

In [31]:
iris_arr[n,:]

array([[5.1, 3.5, 1.4, 0.2, 'setosa'],
       [4.9, 3.0, 1.4, 0.2, 'setosa']], dtype=object)